### PR TITLE
Add support for DETS backed feature toggles

### PR DESCRIPTION
**Pull request by nithinbekal**
To use `Laboratory` in places other than controllers and views (eg. channels), we need to store the features in a way that doesn't require access to the `conn` object. I've added a DETS backend via `Laboratory.DetsStore`, which allows us to use `Laboratory.enabled?(:feature_id)`. I've moved the cookie persistence logic to `Laboratory.CookieStore`.

The idea is to be able to configure the storage based on config variables.

``` elixir
config :laboratory,
  store: Laboratory.DetsStore,
  features: [ ... ]
```

@emilsoman Do we still need cookie store? `DetsStore` already covers all the cases that cookies cover, but `CookieStore` adds complexity because we need to pass the resulting connection object back to browser in `router.ex`.

### CODE REVIEW

**Comment by nithinbekal** [comment]
@emilsoman I've removed the cookie based backend and made the DETS based backend the default. Let me know what you think.

**Comment by fbjork** [comment]
Any progress on this?

**Comment by emilsoman** [comment]
@fbjork I was waiting to test this in an app before merging, but unfortunately couldn't find time, sorry! Have you tried this branch in your app?

**Comment by nithinbekal** [comment]
@emilsoman @fbjork Feel free to ping me if there's anything I can help with here, or if we need changes in the PR. :)

**Comment by nithinbekal** [comment]
Cleaning up outdated issues/PRs that I created. Feel free to reopen if this is still relevant.

**Pull request closed without merging**
